### ISSUE TITLE
NPE if no services defined

### ISSUE THREAD

**Issue by srl295** [ActiveState/cloudfoundry-jenkins#4]
I'm seeing this in 1.4.1. Yes, this is on a job that was upgraded. 

```
Cloud Foundry Plugin:
java.lang.NullPointerException
    at com.activestate.cloudfoundryjenkins.CloudFoundryPushPublisher.perform(CloudFoundryPushPublisher.java:136)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
    at hudson.model.Run.execute(Run.java:1766)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:381)
```

Printfs showed that `perform()` was called, but the `CloudFoundryPushPublisher()` constructor was _not_, leaving a null pointer `servicesToCreate`. Let's reflect on how this might have happened.

I saw this issue discussed elsewhere, can't remember where though.
_Edit_ https://issues.jenkins-ci.org/browse/JENKINS-28885

**Comment by srl295** [comment]
Jenkins 1.620, Red Hat Enterprise Linux.

Strange. I added the following field.. the constructor isn't being called, nor the empty constructor (if I add one). My field `stackJunk` is  `null` inside  `perform()`. 

```
    public CharSequence stackJunk = "<unset>";
    {
        stackJunk = "init: " + getCurrentStack();
    }
```

**Comment by WGautier** [comment]
Thanks for the digging!
Discussion continued on the JIRA bug: https://issues.jenkins-ci.org/browse/JENKINS-28885

**Comment by srl295** [comment]
@WGautier Welcome! 

P.S. you can turn off issues in GitHub if you only keep them in JIRA, maybe with an update to the `README.md` telling people where to file bugs. I had found the JIRA issue with a web search, then opened the issue after I hit the repo.
